### ISSUE TITLE
Using the translation class in multiple folders

### ISSUE THREAD

**Issue by QuentinCG** [InterativaDigital/php-translation-class#2]
Hello ;)

First of all: Thank you for this library.
It works really nicely and I'm currently using it for my website/game project.

I just wanted to know if there was an other way than putting the `localesDir` variable to its absolute path (`protected static $localesDir =  '/var/www/.../locales'` [here](https://github.com/InterativaDigital/php-translation-class/blob/master/Translation.php#L12)) when we want to include this library in PHP files from numerous directories (example: Use translation lib in `/var/www/dummy/index.php` and from `/var/www/dummy/subdir/subsub/index.php`)?

If I don't do that, the library doesn't find the locales directory :( ).
It's not a critical issue but it is a bit "dirty" for me to use an absolute path since I don't want server dependent variables in my project.

I'm not an expert on PHP so my question may be stupid...

Best regards,
Quentin

**Comment by felladrin** [comment]
Hey there!

Thanks for your feedback! We're glad to see it has been put to good use.

The `Translation` class have a public method [`setLocalesDir($localesDir)`](https://github.com/InterativaDigital/php-translation-class/blob/master/Translation.php#L79) that can be used to solve this problem, using relative or absolute paths. So, right after importing the translation lib you just need to call it once, for each of your subdirectories. Don't need to manually set the directory on the lib code.

Taking your example:

On `/var/www/dummy/index.php` you'd have:
```php
<?php
require_once __DIR__ . '/lib/php-translation-class/Translation.php';
use Translation\Translation;
Translation::setLocalesDir(__DIR__ . '/locales');
// Now anything below will be using locales from the path '/var/www/dummy/locales'
Translation::of('greetings');
```

And on `/var/www/dummy/subdir/subsub/index.php` you'd have:
```php
<?php
require_once __DIR__ . '/lib/php-translation-class/Translation.php';
use Translation\Translation;
Translation::setLocalesDir(__DIR__ . '/../../locales');
// Now anything below will be using locales from the path '/var/www/dummy/locales'
Translation::of('greetings');
```

Please, let us know if it works for you.

Regards,
Victor

**Comment by QuentinCG** [comment]
It works like a charm 👍 

Thanks a lot!
